config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except:[:show]
  get 'portfolio/:id', to: 'portfolios#show',as: 'portfolio_show'

  resources :blogs

  get 'About-Me', to: 'pages#About'
  get 'Contact', to: 'pages#Contact'
  get 'Home', to: 'pages#Home'

  resources :blogs do
    member do
      get :toggle_status
    end
  end


  root to: 'pages#Home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft:0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url , notice:'Blog post status has been changed'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
    @posts = Blog.all
    @skills = Skill.all
  end

  def About
  end

  def Contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
def index
  @portfolio_items = Portfolio.all
end

  def new
  @portfolio_items = Portfolio.new
  end

def create
  @portfolio_items = Portfolio.new(params.require(:portfolio).permit(:titile,:subtitle,:body))

  respond_to do |format|
    if @portfolio_items.save
      format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
    else
      format.html { render :new }
    end
  end
end

def edit
  @portfolio_items = Portfolio.find(params[:id])
end

  def update
    @portfolio_items = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_items.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        format.html {redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.'}
      else
        format.html {render :edit}
      end
    end
  end

def show
  @portfolio_items = Portfolio.find(params[:id])
end

  def destroy
    # perform  the look up
    @portfolio_items = Portfolio.find(params[:id])

    # Destroy/Delete the record
    @portfolio_items.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully deleted.' }
    end
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path%>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarvinBabaPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/About.html.erb
<h1>Pages#About</h1>
<p>Find me in app/views/pages/About.html.erb</p>

app/views/pages/Contact.html.erb
<h1>Pages#Contact</h1>
<p>Find me in app/views/pages/Contact.html.erb</p>

app/views/pages/Home.html.erb
<h1>Home Page</h1>
<p>Find me in app/views/pages/Home.html.erb</p>

<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= form_with(model: @portfolio_items, local: true) do |form| %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :subtitle %>
      <%= form.text_area :subtitle %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to"Create New Item",new_portfolio_url %>


<% @portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title,portfolio_show_path(portfolio_item.id) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <p><%= portfolio_item.thumb_image %></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id)%>
    <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/portfolios/new.html.erb
<h1>Create a New Portfolio Item</h1>

<%= form_with(model: @portfolio_items, local: true) do |form| %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :subtitle %>
      <%= form.text_area :subtitle %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/portfolios/show.html.erb
<h1><%= image_tag @portfolio_items.main_image%></h1>

<em><%= @portfolio_items.subtitle %> </em>

<p><%= @portfolio_items.body%></p>